---
include:
  - project: invenia/gitlab-ci-helper
    file: /templates/python.yml
  - project: invenia/gitlab-ci-helper
    file: /templates/coverage.yml

# coverage.yml will include the "Coverage" teardown job

"Check Code Format/Typing":
  stage: setup
  extends: .py_3_8
  script:
    - tox -re formatting,types

"Test Python 3.8":
  extends: .test_3_8

"Version Check":
  extends: .version_check

"Test PyPI Build":
  extends: .test_dist

"Upload to Private PyPI":
  extends: .upload_to_private_pypi
